include:
  - ./storage/docker-compose.yml
  - ./kong/docker-compose.yml
  - ./grafana/docker-compose.yml
  - ./vault/docker-compose.yml
  - ../microservices/backoffice/docker/docker-compose.yml

services:
  reels_postgres:
    image: postgres
    container_name: reels_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reels_backoffice
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reels_network

networks:
  reels_network:
      driver: bridge

volumes:
  postgres_data: